# Generated by Django 5.1.2 on 2024-11-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Укажите дату выхода'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(null=True, verbose_name='Укажите цену'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Укажите описание книги'),
        ),
    ]
